// Assembles the npm "package" that the Claude Design converter needs, from
// the registry in .design-sync/components.mjs. Adding a component to the
// design system is one row there and nothing here.
//
// This repo has no package.json, no JS build and no Storybook: the UI is
// Preact + htm loaded from an importmap. The converter cannot read that, so
// this builds a throwaway package around the same sources.
//
//   1. copies src/sm64_events/ui into a work dir, minus its vendor/ copies,
//      so the bare specifiers resolve to the shim and the real htm
//   2. installs react/react-dom/htm and drops the preact->React shim in as
//      node_modules/preact
//   3. inlines the registry's asset directories as data URIs and rewrites
//      every /ui/assets path to read them -- those are absolute paths that
//      exist only behind this app's own server, so a design rendered
//      anywhere else would 404 every one of them
//   4. generates the bundle entry, the .d.ts contract and one doc per
//      component from the registry
//   5. bundles an ESM entry with react/react-dom left external
//
// Then run the converter against it:
//   node .ds-sync/resync.mjs --config .design-sync/config.json \
//     --node-modules .ds-sync/facade-build/node_modules \
//     --entry .ds-sync/facade-build/dist/index.js --out ./ds-bundle
//
// usage: node .design-sync/facade/build.mjs [workDir]

import { execFileSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { ASSET_DIRS, ASSET_FILES, COMPONENTS, PREAMBLE } from "../components.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, "..", "..");
const work = resolve(process.argv[2] || join(repo, ".ds-sync", "facade-build"));
const uiDir = join(repo, "src", "sm64_events", "ui");

const die = (message) => { console.error(`✗ ${message}`); process.exit(1); };

console.log(`facade -> ${work}`);
rmSync(join(work, "src"), { recursive: true, force: true });
rmSync(join(work, "docs"), { recursive: true, force: true });
mkdirSync(join(work, "src"), { recursive: true });
mkdirSync(join(work, "dist"), { recursive: true });
mkdirSync(join(work, "docs"), { recursive: true });

// ---- 1. sources ---------------------------------------------------------
cpSync(uiDir, join(work, "src"), { recursive: true });
rmSync(join(work, "src", "vendor"), { recursive: true, force: true });

// The whole design system is one <style> block inside index.html -- there is
// no stylesheet file to point cfg.cssEntry at, so lift it out. Losing this
// step is silent and total: every card renders on white with no tokens, and
// the render check still passes because the components themselves mount.
const indexHtml = readFileSync(join(uiDir, "index.html"), "utf8");
const styleOpen = indexHtml.indexOf("<style>");
const styleClose = indexHtml.indexOf("</style>", styleOpen);
if (styleOpen < 0 || styleClose < 0) {
  die("index.html has no <style> block -- the design system CSS could not be lifted, and every design would render unstyled");
}
const designCss = indexHtml.slice(styleOpen + "<style>".length, styleClose);
if (!designCss.includes(":root") || !designCss.includes("--bg:")) {
  die("the lifted <style> block defines no :root tokens -- check index.html before shipping a token-less design system");
}
writeFileSync(join(work, "src", "styles.css"), designCss);
console.log(`lifted design system CSS: ${(designCss.length / 1024).toFixed(0)} KB`);

// ---- 2. assets ----------------------------------------------------------
const assets = {};
const addAsset = (webPath, diskPath) => {
  const ext = webPath.slice(webPath.lastIndexOf(".") + 1).toLowerCase();
  const mime = ext === "png" ? "image/png" : ext === "webp" ? "image/webp"
    : ext === "jpg" || ext === "jpeg" ? "image/jpeg" : "application/octet-stream";
  assets[webPath] = `data:${mime};base64,${readFileSync(diskPath).toString("base64")}`;
};
for (const dir of ASSET_DIRS) {
  const diskDir = join(uiDir, "assets", dir);
  if (!existsSync(diskDir)) die(`ASSET_DIRS names "${dir}", which is not under ui/assets`);
  for (const name of readdirSync(diskDir)) {
    if (name.endsWith(".ttf") || name.endsWith(".woff2")) continue; // fonts ship via extraFonts
    addAsset(`/ui/assets/${dir}/${name}`, join(diskDir, name));
  }
}
for (const name of ASSET_FILES) {
  const diskPath = join(uiDir, "assets", name);
  if (!existsSync(diskPath)) die(`ASSET_FILES names "${name}", which is not under ui/assets`);
  addAsset(`/ui/assets/${name}`, diskPath);
}
const inlinedBytes = Object.values(assets).reduce((total, uri) => total + uri.length, 0);
writeFileSync(
  join(work, "src", "ds-assets.js"),
  "// Generated by .design-sync/facade/build.mjs from components.mjs's ASSET_DIRS.\n" +
  "// A path that is not here keeps its original value and warns -- which in a\n" +
  "// design renders as a broken image, so add its directory to the registry.\n" +
  `const ASSETS = ${JSON.stringify(assets, null, 0)};\n` +
  "export function DS_ASSET(path) {\n" +
  "  const inlined = ASSETS[path];\n" +
  "  if (inlined) return inlined;\n" +
  "  console.warn('[ds-assets] not inlined, will 404 in a design:', path);\n" +
  "  return path;\n" +
  "}\n"
);
console.log(`inlined ${Object.keys(assets).length} assets (${(inlinedBytes / 1024 / 1024).toFixed(2)} MB base64)`);

// The cap art is the one site that composes a directory base rather than a
// whole path, so the generic rewrite below cannot see it.
const PATCHES = [
  {
    file: "components/hat.js",
    find: 'const HAT_DIR = "/ui/assets/hat";\nconst art = (stem) => `url(${HAT_DIR}/${stem}.png)`;',
    replace: 'const art = (stem) => `url(${DS_ASSET(`/ui/assets/hat/${stem}.png`)})`;',
  },
];

const ASSET_TEMPLATE = /`\/ui\/assets\/[^`]*`/g;
const IMPORT_MARK = "/* ds-assets */";
let rewritten = 0;

function walk(dir) {
  for (const name of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, name.name);
    if (name.isDirectory()) { walk(full); continue; }
    if (!name.name.endsWith(".js") || name.name === "ds-assets.js") continue;
    const relPath = relative(join(work, "src"), full).replace(/\\/g, "/");
    let source = readFileSync(full, "utf8");
    const before = source;
    for (const patch of PATCHES.filter((entry) => entry.file === relPath)) {
      if (!source.includes(patch.find)) {
        die(`${relPath}: patch anchor not found. The art it covers would 404 in every design — re-anchor this patch against the current source, never drop it.`);
      }
      source = source.replace(patch.find, patch.replace);
    }
    source = source.replace(ASSET_TEMPLATE, (match) => `DS_ASSET(${match})`);
    if (source === before) continue;
    const depth = relPath.split("/").length - 1;
    const importPath = `${depth ? "../".repeat(depth) : "./"}ds-assets.js`;
    source = `import { DS_ASSET } from "${importPath}"; ${IMPORT_MARK}\n${source}`;
    writeFileSync(full, source);
    rewritten++;
  }
}
walk(join(work, "src"));
if (!rewritten) die("no /ui/assets site was rewritten — the scan is broken, and every image would 404 in a design");
console.log(`rewrote asset paths in ${rewritten} file(s)`);

// ---- 3. entry, contract and docs, all from the registry -----------------
const entryLines = COMPONENTS.map((component) => {
  const names = [component.export || component.name, ...(component.also || [])];
  return `export { ${names.join(", ")} } from "${component.module}";`;
});
// Exported so previews (and designs) can reach the inlined art the same way
// the components do. Not PascalCase, so the converter never mistakes it for
// a component -- and a preview that writes a raw /ui/assets path instead
// gets a broken-image box, because nothing rewrites a file outside src/.
entryLines.push('export { DS_ASSET } from "./ds-assets.js";');
writeFileSync(join(work, "src", "index.js"), entryLines.join("\n") + "\n");

const dts = [PREAMBLE];
for (const component of COMPONENTS) {
  const body = component.props
    .map(([name, type, doc]) => `  /** ${doc} */\n  ${name}: ${type};`)
    .join("\n");
  dts.push(`/** ${component.doc} */\nexport interface ${component.name}Props {\n${body}\n}`);
  dts.push(`export declare const ${component.name}: React.FC<${component.name}Props>;\n`);
}
writeFileSync(join(work, "dist", "index.d.ts"), dts.join("\n"));

for (const component of COMPONENTS) {
  const rows = component.props
    .map(([name, type, doc]) => `| \`${name}\` | \`${type}\` | ${doc} |`)
    .join("\n");
  writeFileSync(
    join(work, "docs", `${component.name}.md`),
    `---\ncategory: ${component.group}\n---\n\n# ${component.name}\n\n${component.doc}\n\n` +
    `| Prop | Type | Notes |\n|---|---|---|\n${rows}\n`
  );
}
console.log(`registry: ${COMPONENTS.length} components in ${new Set(COMPONENTS.map((c) => c.group)).size} groups`);

// ---- 4. deps and the shim -----------------------------------------------
cpSync(join(here, "package.json"), join(work, "package.json"));
cpSync(join(here, "supermario256.css"), join(work, "src", "assets", "fonts", "supermario256.css"));
if (!existsSync(join(work, "node_modules", "react"))) {
  console.log("installing react, react-dom, htm ...");
  execFileSync("npm", ["i", "--silent", "react", "react-dom", "htm", "@types/react"], { cwd: work, stdio: "inherit", shell: true });
}
cpSync(join(here, "preact"), join(work, "node_modules", "preact"), { recursive: true });

// ---- 5. bundle ----------------------------------------------------------
const esbuild = join(repo, ".ds-sync", "node_modules", "@esbuild", "win32-x64", "esbuild.exe");
if (!existsSync(esbuild)) die(`esbuild not staged at ${esbuild} — see .design-sync/NOTES.md for the .ds-sync setup`);
execFileSync(esbuild, [
  "src/index.js", "--bundle", "--format=esm", "--outfile=dist/index.js",
  "--external:react", "--external:react-dom", "--external:react-dom/client",
], { cwd: work, stdio: "inherit" });

console.log(`\n--node-modules ${join(work, "node_modules")}`);
console.log(`--entry ${join(work, "dist", "index.js")}`);
