"""ui/logtuning.js — the registry the practice-log card inspector is
generated from.

Structurally different from climbtuning.js/marelotuning.js in ONE way that
matters here: nothing in this registry is consumed by a JS animation loop.
Every row is consumed by CSS, through a custom property (`--log-<kebab-key>`,
generated by the registry's own `cssVarName`) or a modifier class
(`<cssPrefix>-<option>`, generated by `logTuningClasses`) on `.log-list-card`
in index.html. So the two failure modes climbtuning.js's guards exist for
still apply, just aimed at index.html instead of a sibling .js file:

  * A DEAD CONTROL. A tunable/choice nobody's CSS references renders a
    slider that changes nothing on screen.
  * AN UNDEFINED READ. A `var(--log-x)` in index.html for an `x` the
    registry does not declare falls back silently (an invalid length just
    fails to apply), which looks identical to the control doing nothing.

Both scans run against index.html's text, comment-stripped with a plain CSS
`/* ... */` stripper (index.html has no `//` comments to worry about, unlike
the JS `code_only` climbtuning.js's guards use). Every scan is proved by
mutation against a `tmp_path` copy of index.html's real text, never by
editing the tracked file in place -- a sibling session may run this suite
in the same worktree.
"""
import json
import re
import shutil
import subprocess
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
UI = REPO / "src" / "sm64_events" / "ui"
TUNING_JS = UI / "logtuning.js"
INDEX_HTML = UI / "index.html"

pytestmark = pytest.mark.skipif(shutil.which("node") is None,
                                reason="node not on PATH")


def run_node(imports: str, body: str, module: Path = TUNING_JS):
    script = f"import {{ {imports} }} from {module.as_uri()!r};\n{body}"
    result = subprocess.run(["node", "--input-type=module", "-"],
                            input=script, capture_output=True, text=True, timeout=60)
    assert result.returncode == 0, result.stderr
    return json.loads(result.stdout)


def registry() -> dict:
    """Every fact this test file needs, sourced from the REAL module rather
    than restated -- `varNames`/`vars`/`classes` come from the registry's OWN
    `cssVarName`/`logTuningVars`/`logTuningClasses`, never a Python
    reimplementation of the camelCase-to-kebab-case rule (which would be a
    second door: it could drift from the real one and this suite would never
    notice)."""
    return run_node(
        "TUNABLES, CHOICES, DEFAULTS, cssVarName, logTuningVars, logTuningClasses",
        "const varNames = Object.fromEntries("
        "  Object.keys(TUNABLES).map((key) => [key, cssVarName(key)]));\n"
        "console.log(JSON.stringify({\n"
        "  tunables: TUNABLES, choices: CHOICES, defaults: DEFAULTS,\n"
        "  varNames, vars: logTuningVars(DEFAULTS), classes: logTuningClasses(DEFAULTS),\n"
        "}));")


# ---- The two CSS-side scans, as plain functions of text -------------------
#
# Written as functions of a STRING rather than inline in each test, so the
# mutation-proof tests below can feed them a hand-built sample: a raw
# substring search cannot tell code from a comment describing that code
# (tests/source_scan.py's own five-times-bitten lesson, restated here for CSS
# since index.html has no code_only() equivalent to import).

def strip_css_comments(css: str) -> str:
    return re.sub(r"/\*.*?\*/", "", css, flags=re.S)


def missing_var_reads(css_text: str, var_names: dict) -> list:
    """Tunable keys whose OWN custom property is never read by a `var(...)`
    anywhere in the given CSS text."""
    css = strip_css_comments(css_text)
    return sorted(key for key, var in var_names.items()
                  if not re.search(rf"var\(\s*{re.escape(var)}\b", css))


def unknown_var_reads(css_text: str, known_vars: set) -> list:
    """The inverse: every `--log-*` a `var(...)` call in the CSS names that
    is not one of the registry's own custom properties."""
    css = strip_css_comments(css_text)
    used = set(re.findall(r"var\(\s*(--log-[a-z-]+)", css))
    return sorted(used - known_vars)


def missing_choice_reads(css_text: str, choices: dict) -> list:
    """Choice options with no modifier-class selector anywhere in the CSS --
    the choice-row equivalent of a dead tunable."""
    css = strip_css_comments(css_text)
    missing = []
    for key, row in choices.items():
        for option in row["options"]:
            cls = f".{row['cssPrefix']}-{option.lower()}"
            if cls not in css:
                missing.append(f"{key}:{option}")
    return missing


def unknown_choice_classes(css_text: str, choices: dict) -> list:
    """The inverse: a modifier class under one of this registry's own
    prefixes that names no real option -- a typo (`log-rankstyle-cap`) reads
    identically to a control doing nothing, the same failure a stray
    `var(--log-x)` is."""
    css = strip_css_comments(css_text)
    prefixes = {row["cssPrefix"] for row in choices.values()}
    valid = {f"{row['cssPrefix']}-{option.lower()}"
             for row in choices.values() for option in row["options"]}
    found = set()
    for prefix in prefixes:
        found |= set(re.findall(rf"\.({re.escape(prefix)}-[a-z]+)\b", css))
    return sorted(found - valid)


# ---- The guards themselves --------------------------------------------------

def test_every_tunable_is_actually_read_by_the_css():
    data = registry()
    missing = missing_var_reads(INDEX_HTML.read_text(encoding="utf-8"), data["varNames"])
    assert not missing, (
        f"ui/logtuning.js declares {missing}, whose custom property index.html "
        "never reads with var(...). The inspector would render a control that "
        "changes nothing on screen.")


def test_no_css_reads_a_log_var_that_does_not_exist():
    data = registry()
    known = set(data["varNames"].values())
    unknown = unknown_var_reads(INDEX_HTML.read_text(encoding="utf-8"), known)
    assert not unknown, (
        f"{unknown} are read by var(...) in index.html but declared nowhere in "
        "logtuning.js -- each one silently falls back, which looks identical "
        "to the control doing nothing.")


def test_every_choice_option_is_actually_read_by_the_css():
    data = registry()
    missing = missing_choice_reads(INDEX_HTML.read_text(encoding="utf-8"), data["choices"])
    assert not missing, (
        f"{missing} have no `.{{cssPrefix}}-{{option}}` selector anywhere in "
        "index.html -- picking that option would look identical to any other.")


def test_no_css_reads_a_choice_class_that_does_not_exist():
    data = registry()
    unknown = unknown_choice_classes(INDEX_HTML.read_text(encoding="utf-8"), data["choices"])
    assert not unknown, (
        f"{unknown} are styled in index.html but name no real option in "
        "logtuning.js's CHOICES -- a likely typo of a real modifier class.")


# ---- Mutation proofs, over tmp_path copies of the REAL text ----------------
#
# Never the tracked file: a sibling session may be running this same suite in
# this same worktree, and an in-place mutate-then-revert is what produced
# this branch's own phantom flaky-test count (see CLAUDE.md's dev-process
# rules). Each proof copies the real index.html text into a tmp_path file,
# mutates ONLY the in-memory string handed to the scan, and confirms both
# that the mutation trips the guard and that the REAL text does not.

def test_the_tunable_reader_guard_can_fail(tmp_path):
    data = registry()
    real_css = INDEX_HTML.read_text(encoding="utf-8")
    victim_var = data["varNames"]["iconSize"]
    mutated = tmp_path / "index.html"
    # The replacement must not CONTAIN the original name as a substring: a
    # trailing "-disconnected" still satisfies `\b` right after "size" (a
    # word/non-word boundary sits between the letter and the hyphen), so the
    # scan's own regex would keep matching the "mutated" text. A wholly
    # different name is the only way to actually disconnect it.
    mutated.write_text(real_css.replace(victim_var, "--totally-unrelated-name"),
                       encoding="utf-8")
    missing_here = missing_var_reads(mutated.read_text(encoding="utf-8"), data["varNames"])
    assert "iconSize" in missing_here
    assert "iconSize" not in missing_var_reads(real_css, data["varNames"]), (
        "the real file already fails this check -- the mutation proved nothing")


def test_the_unknown_var_guard_can_fail(tmp_path):
    data = registry()
    real_css = INDEX_HTML.read_text(encoding="utf-8")
    mutated = tmp_path / "index.html"
    mutated.write_text(
        real_css + "\n/* injected by a mutation test */\n"
        ".tuning-mutation-probe { width: var(--log-does-not-exist); }\n",
        encoding="utf-8")
    known = set(data["varNames"].values())
    assert "--log-does-not-exist" in unknown_var_reads(mutated.read_text(encoding="utf-8"), known)
    assert not unknown_var_reads(real_css, known), (
        "the real file already fails this check -- the mutation proved nothing")


def test_the_choice_reader_guard_can_fail(tmp_path):
    data = registry()
    real_css = INDEX_HTML.read_text(encoding="utf-8")
    mutated = tmp_path / "index.html"
    # Every occurrence of the "centred" option's own class, gone -- as if
    # nobody had wired that branch of identityAlign at all.
    mutated.write_text(real_css.replace("log-align-centred", "log-align-DISCONNECTED"),
                       encoding="utf-8")
    missing_here = missing_choice_reads(mutated.read_text(encoding="utf-8"), data["choices"])
    assert "identityAlign:centred" in missing_here
    assert "identityAlign:centred" not in missing_choice_reads(real_css, data["choices"]), (
        "the real file already fails this check -- the mutation proved nothing")


def test_the_unknown_choice_class_guard_can_fail(tmp_path):
    data = registry()
    real_css = INDEX_HTML.read_text(encoding="utf-8")
    mutated = tmp_path / "index.html"
    mutated.write_text(
        real_css + "\n/* injected by a mutation test */\n"
        ".log-rankstyle-wide-two-typo { opacity: .5; }\n",
        encoding="utf-8")
    unknown_here = unknown_choice_classes(mutated.read_text(encoding="utf-8"), data["choices"])
    assert "log-rankstyle-wide-two-typo" in unknown_here
    assert not unknown_choice_classes(real_css, data["choices"]), (
        "the real file already fails this check -- the mutation proved nothing")


# ---- Registry shape + round-trip tests, mirroring climbtuning.js's own ----

def test_every_row_is_complete_enough_to_render_a_control():
    data = registry()
    for name, row in data["tunables"].items():
        assert row.get("group") and row.get("label") and row.get("why"), name
        for field in ("value", "min", "max", "step"):
            assert isinstance(row.get(field), (int, float)), f"{name}.{field}"
        assert row["min"] <= row["value"] <= row["max"], (
            f"{name} ships at {row['value']}, outside its own {row['min']}"
            f"..{row['max']} range -- the slider could not even show it")
    for name, row in data["choices"].items():
        assert row.get("group") and row.get("label") and row.get("why"), name
        assert row.get("cssPrefix"), f"{name} has no cssPrefix to build a class from"
        assert row["value"] in row["options"], name


def test_a_tunable_never_collides_with_a_choice():
    data = registry()
    both = set(data["tunables"]) & set(data["choices"])
    assert not both, f"{both} is declared twice; one silently wins in DEFAULTS"


def test_css_var_names_are_unique_and_well_formed():
    data = registry()
    names = list(data["varNames"].values())
    assert len(names) == len(set(names)), "two tunables collided on one custom property"
    assert all(re.fullmatch(r"--log-[a-z0-9-]+", name) for name in names), names


def test_logtuning_vars_reproduces_the_shipped_defaults():
    """The golden property: every value here replaced a fallback literal in
    index.html's own `var(--log-x, <fallback>)`, so with the registry at its
    defaults the vars logTuningVars produces must equal those fallbacks --
    if this drifts, a tunable's default silently disagrees with what the app
    would render before any tuning ever ran."""
    data = registry()
    css = INDEX_HTML.read_text(encoding="utf-8")
    for key, var in data["varNames"].items():
        fallback_match = re.search(rf"var\(\s*{re.escape(var)}\s*,\s*([^)]+)\)", css)
        assert fallback_match, f"no fallback found for {var} in index.html"
        fallback = fallback_match.group(1).strip()
        assert fallback == data["vars"][var], (
            f"{key}: registry says {data['vars'][var]!r}, index.html's own "
            f"var() fallback says {fallback!r} -- they must agree")


def test_a_tuning_change_actually_changes_the_vars():
    """The inverse of the golden test, proving it has teeth: a changed value
    must reach the vars object, or logTuningVars could ignore its argument
    entirely and the golden test above would still pass."""
    data = run_node(
        "DEFAULTS, logTuningVars",
        "console.log(JSON.stringify(logTuningVars("
        "  { ...DEFAULTS, bodyIndent: 999, bodyTint: 0.5 })));")
    assert data["--log-body-indent"] == "999px"
    assert data["--log-body-tint"] == "0.5"


def test_logtuning_classes_cover_every_choice():
    data = registry()
    classes = data["classes"].split(" ")
    assert len(classes) == len(data["choices"])
    for row in data["choices"].values():
        assert any(cls.startswith(f"{row['cssPrefix']}-") for cls in classes), row


def test_a_tuning_change_actually_changes_the_classes():
    data = run_node(
        "DEFAULTS, logTuningClasses",
        "console.log(JSON.stringify(logTuningClasses("
        "  { ...DEFAULTS, rankStyleWideTwoLadders: 'capsOnly' })));")
    assert "log-rankstyle-wide-two-capsonly" in data.split(" ")


def test_the_settings_string_round_trips_every_value():
    same, keys, defaults_count = run_node(
        "encodeTuning, decodeTuning, DEFAULTS",
        "const mine = { ...DEFAULTS, bodyIndent: 40, rankStyleWideOneLadder: 'banners' };\n"
        "const round = decodeTuning(encodeTuning(mine));\n"
        "console.log(JSON.stringify([\n"
        "  JSON.stringify(round) === JSON.stringify(mine),\n"
        "  Object.keys(JSON.parse(encodeTuning(mine))).length,\n"
        "  Object.keys(DEFAULTS).length]));")
    assert same, "a settings string did not survive its own round trip"
    assert keys == defaults_count, "the string must carry EVERY value"


def test_decoding_drops_unknown_keys_and_fills_missing_ones():
    result = run_node(
        "decodeTuning, DEFAULTS",
        "const got = decodeTuning(JSON.stringify("
        "  { iconSize: 55, aTunableWeDeleted: 9 }));\n"
        "console.log(JSON.stringify([got.iconSize,\n"
        "  'aTunableWeDeleted' in got, got.rowHeight === DEFAULTS.rowHeight]));")
    assert result == [55, False, True]


def test_changed_from_default_is_only_what_moved():
    changed = run_node(
        "changedFromDefault, DEFAULTS",
        "console.log(JSON.stringify(changedFromDefault("
        "  { ...DEFAULTS, cardGap: 20 })));")
    assert changed == {"cardGap": 20}


def test_the_active_slot_defaults_and_can_be_set():
    result = run_node(
        "logTuning, setLogTuning, DEFAULTS",
        "const before = logTuning().iconSize === DEFAULTS.iconSize;\n"
        "setLogTuning({ iconSize: 61 });\n"
        "const after = logTuning().iconSize;\n"
        "console.log(JSON.stringify([before, after]));")
    assert result == [True, 61]


# ---- rankPlacementFor / nextStepModeFor (spec practice-log-entity-cards, --
# round 3) -- practicelog.js's own per-section resolvers, pure and node-
# tested for the same reason every other decision function in this codebase
# is: the CALLER (practicelog.js) is the only place that should ever have to
# know which of the four registry rows applies to a given section.

def test_rank_placement_resolves_all_four_cells_independently():
    result = run_node(
        "DEFAULTS, rankPlacementFor",
        "const tuning = { ...DEFAULTS,\n"
        "  rankPlacementNarrowTwoLadders: 'body',\n"
        "  rankPlacementNarrowOneLadder: 'head',\n"
        "  rankPlacementWideTwoLadders: 'head',\n"
        "  rankPlacementWideOneLadder: 'body' };\n"
        "console.log(JSON.stringify([\n"
        "  rankPlacementFor(tuning, { isNarrow: true, twoLadder: true }),\n"
        "  rankPlacementFor(tuning, { isNarrow: true, twoLadder: false }),\n"
        "  rankPlacementFor(tuning, { isNarrow: false, twoLadder: true }),\n"
        "  rankPlacementFor(tuning, { isNarrow: false, twoLadder: false }),\n"
        "]));")
    assert result == ["body", "head", "head", "body"]


def test_rank_placement_ships_head_at_every_cell():
    """The shipped default is a genuine no-op -- Griffin asked to "test this
    out", not committing to a shape yet, same convention as identityCondense."""
    result = run_node(
        "DEFAULTS, rankPlacementFor",
        "console.log(JSON.stringify([\n"
        "  rankPlacementFor(DEFAULTS, { isNarrow: true, twoLadder: true }),\n"
        "  rankPlacementFor(DEFAULTS, { isNarrow: true, twoLadder: false }),\n"
        "  rankPlacementFor(DEFAULTS, { isNarrow: false, twoLadder: true }),\n"
        "  rankPlacementFor(DEFAULTS, { isNarrow: false, twoLadder: false }),\n"
        "]));")
    assert result == ["head", "head", "head", "head"]


def test_next_step_mode_resolves_all_four_cells_independently():
    result = run_node(
        "DEFAULTS, nextStepModeFor",
        "const tuning = { ...DEFAULTS,\n"
        "  nextStepNarrowTwoLadders: 'hidden',\n"
        "  nextStepNarrowOneLadder: 'compact',\n"
        "  nextStepWideTwoLadders: 'hover',\n"
        "  nextStepWideOneLadder: 'always' };\n"
        "console.log(JSON.stringify([\n"
        "  nextStepModeFor(tuning, { isNarrow: true, twoLadder: true }),\n"
        "  nextStepModeFor(tuning, { isNarrow: true, twoLadder: false }),\n"
        "  nextStepModeFor(tuning, { isNarrow: false, twoLadder: true }),\n"
        "  nextStepModeFor(tuning, { isNarrow: false, twoLadder: false }),\n"
        "]));")
    assert result == ["hidden", "compact", "hover", "always"]


def test_next_step_mode_ships_hover_narrow_always_wide():
    """Griffin's own words did the narrow/wide split: "present this as simply
    and screen-space efficiently as possible... especially in narrow display
    mode. Maybe we don't actually even display it at all, until hover?" """
    result = run_node(
        "DEFAULTS, nextStepModeFor",
        "console.log(JSON.stringify([\n"
        "  nextStepModeFor(DEFAULTS, { isNarrow: true, twoLadder: true }),\n"
        "  nextStepModeFor(DEFAULTS, { isNarrow: true, twoLadder: false }),\n"
        "  nextStepModeFor(DEFAULTS, { isNarrow: false, twoLadder: true }),\n"
        "  nextStepModeFor(DEFAULTS, { isNarrow: false, twoLadder: false }),\n"
        "]));")
    assert result == ["hover", "hover", "always", "always"]


def test_the_narrow_breakpoint_constant_matches_the_layout_matrix_css():
    """practicelog.js's own ResizeObserver has to agree with the "Layout
    matrix" CSS section's `@container (max-width: 860px)` -- the one number
    in two places this file's own NARROW_CONTAINER_PX comment names. Same
    shape as desktop/window.py::MIN_WINDOW_WIDTH vs.
    uilab_project.py::min_viewport_width."""
    narrow_px = run_node("NARROW_CONTAINER_PX", "console.log(JSON.stringify(NARROW_CONTAINER_PX));")
    css = INDEX_HTML.read_text(encoding="utf-8")
    marker = css.index("Layout matrix")
    end = css.index("Rank placement --", marker)
    section = css[marker:end]
    assert f"max-width: {narrow_px}px" in section, (
        f"NARROW_CONTAINER_PX is {narrow_px}, but the 'Layout matrix' CSS "
        "section's own @container threshold does not match it")
