"""Render the reader-neutral rule index from the scoped rules' own metadata.

Run after changing a rule title or paths: `python tools/build_rule_index.py`.
Use --check to report drift without writing. Rule paths remain authoritative;
the generated map gives readers without automatic scoped loading the same routes.
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INDEX = Path("docs/rule-index.md")


def frontmatter_paths(path: Path) -> list[str]:
    """Read the project's fixed, quoted YAML list; reject unscoped metadata."""
    text = path.read_text(encoding="utf-8")
    match = re.match(r"---\n(.*?)\n---\n", text, re.S)
    if not match:
        raise ValueError(f"{path.name}: no YAML frontmatter")
    body = match.group(1)
    if not body.lstrip().startswith("paths:"):
        raise ValueError(f"{path.name}: use paths:, not globs: or unscoped metadata")
    paths = re.findall(r'^\s*-\s*"([^"]+)"\s*$', body, re.M)
    if not paths:
        raise ValueError(f"{path.name}: paths: list is empty")
    return paths


def render_index(root: Path = ROOT) -> str:
    """Derive every route and topic label from the rule it opens."""
    lines = [
        "# Project rule index", "",
        "Generated by `tools/build_rule_index.py` from `.claude/rules/*.md`.",
        "Change a rule's `paths:` or heading, then regenerate; do not edit this map.", "",
        "Before editing, open every rule whose pattern matches the file, including",
        "overlapping zones and chain rules. Paths below are relative to the repo root.",
        "Claude Code loads matching rules automatically; other readers use this map.",
        "For UI work always include `ui-core.md` and the matching surface rules.",
        "Read the relevant tests first; tests mirror their modules.", "",
        "| Rule | Matching paths |", "| --- | --- |",
    ]
    for rule in sorted((root / ".claude/rules").glob("*.md")):
        title = re.search(r"^# (.+)$", rule.read_text(encoding="utf-8"), re.M)
        if not title:
            raise ValueError(f"{rule.name}: no topic heading")
        label = title.group(1).replace("|", "\\|")
        paths = ", ".join(f"`{pattern}`" for pattern in frontmatter_paths(rule))
        lines.append(f"| [{label}](../.claude/rules/{rule.name}) | {paths} |")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render_index()
    destination = ROOT / INDEX
    if args.check:
        if not destination.exists() or destination.read_text(encoding="utf-8") != expected:
            print("Rule index differs; run python tools/build_rule_index.py")
            return 1
        print("Rule index matches scoped metadata")
        return 0
    destination.write_text(expected, encoding="utf-8", newline="\n")
    print(f"Wrote {INDEX.as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
