"""Snapshot Ukikipedia's RTA Guide page titles and report which Library
targets they cover.

    uv run python tools/scrape_ukikipedia.py

The wiki mark (the Ukiki face beside a target's name on the Library tab, and
the drawer's "RTA Guide" link) links only to a page that EXISTS: a link
generated from a star name and hoped for is a 404 the moment the wiki spells
a title differently ("Can the Eel Come out to Play?", "A-maze-ing Emergency
Exit"), and the castle movements have no page at all unless someone wrote one
(LBLJ, Lakitu Skip, MIPS). So this asks the wiki's own API for every page
under `RTA Guide/`, follows each redirect to the page it lands on, and writes
the set to `src/sm64_events/ukikipedia_titles.py` -- a Python module rather
than a data seed so the exe ships it with no --add-data row and no path
helper. `links.py::ukikipedia_url` resolves a target against that set.

READ THE REPORT: the "no page:" list is the deliverable. A castle movement
there is honest (the wiki has no page for "Lobby door (L) - CCM wooden door");
a STAR there means the wiki renamed a page and `links.py` needs a new alias.

Ukikipedia is a MediaWiki: `api.php` answers a polite User-Agent (verified
2026-08-15); the bare page fetches that used to 403 were browser-imitating
requests. Read-only, safe to re-run any time.
"""
from __future__ import annotations

import gzip
import json
import sys
import urllib.parse
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

API = "https://ukikipedia.net/mediawiki/api.php"
PREFIX = "RTA Guide/"
USER_AGENT = "sm64-trainer-linkcheck/1.0 (github.com/griffinbeels/sm64_tracker)"
OUT = REPO / "src" / "sm64_events" / "ukikipedia_titles.py"
LIBRARY_SEED = REPO / "src" / "sm64_events" / "data" / "sheet_library.seed.json.gz"


def api(params: dict) -> dict:
    query = urllib.parse.urlencode({**params, "format": "json"})
    request = urllib.request.Request(f"{API}?{query}",
                                     headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request, timeout=30) as response:
        if response.status != 200:
            raise SystemExit(f"api.php answered {response.status}")
        return json.loads(response.read().decode("utf-8"))


def all_titles() -> list[str]:
    """Every main-namespace page whose title starts with the RTA Guide prefix."""
    titles, cont = [], {}
    while True:
        payload = api({"action": "query", "list": "allpages", "apnamespace": 0,
                       "apprefix": PREFIX, "aplimit": 500, **cont})
        titles.extend(page["title"] for page in payload["query"]["allpages"])
        cont = payload.get("continue")
        if not cont:
            return titles


def resolve_redirects(titles: list[str]) -> dict[str, str]:
    """title -> the page it lands on (itself unless it redirects)."""
    landing = {title: title for title in titles}
    for start in range(0, len(titles), 50):
        batch = titles[start:start + 50]
        payload = api({"action": "query", "titles": "|".join(batch),
                       "redirects": 1})
        for hop in payload["query"].get("redirects", []):
            landing[hop["from"]] = hop["to"]
    # A redirect to a redirect lands where the chain ends (bounded: a loop
    # in the wiki must not loop here).
    for title in titles:
        here = title
        for _ in range(5):
            next_hop = landing.get(here, here)
            if next_hop == here:
                break
            here = next_hop
        landing[title] = here
    return landing


def write_module(landing: dict[str, str], fetched_at: str) -> None:
    lines = [
        '"""Ukikipedia\'s RTA Guide page titles -- GENERATED by',
        "tools/scrape_ukikipedia.py, never edited by hand.",
        "",
        "TITLES maps every page under `RTA Guide/` to the page it lands on (itself,",
        "or its redirect target). `links.py::ukikipedia_url` links a target only",
        "when its candidate title is a key here, so a link this app draws is a page",
        "that existed on FETCHED_AT.",
        '"""',
        f"FETCHED_AT = {fetched_at!r}",
        "",
        "TITLES = {",
    ]
    for title in sorted(landing):
        lines.append(f"    {title!r}: {landing[title]!r},")
    lines.append("}")
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def coverage_report() -> None:
    """Resolve every bundled Library target through the fresh module."""
    import importlib
    import sm64_events.ukikipedia_titles as titles_module
    importlib.reload(titles_module)
    import sm64_events.links as links
    importlib.reload(links)
    payload = json.loads(gzip.open(LIBRARY_SEED, "rb").read().decode("utf-8"))
    resolved, missing = 0, []
    for target in payload["targets"]:
        url = links.ukikipedia_url(target["entity_key"], target["label"])
        if url:
            resolved += 1
        else:
            missing.append(f"{target['group']} :: {target['label']}")
    print(f"targets with a page: {resolved} / {len(payload['targets'])}")
    print(f"no page: {len(missing)}")
    for line in missing:
        print(f"  {line}")


def main() -> None:
    titles = all_titles()
    landing = resolve_redirects(titles)
    fetched_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    write_module(landing, fetched_at)
    redirects = sum(1 for title, to in landing.items() if title != to)
    print(f"{len(titles)} pages under {PREFIX!r} ({redirects} redirects) -> {OUT}")
    coverage_report()


if __name__ == "__main__":
    main()
